In [28]:
import pandas as pd
import numpy as np

In [29]:
df1 = pd.read_csv('stock_data_NSE_grp_quartile.csv')

In [30]:
df1

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,Group,Quartile
0,01-01-2020,20MICRONS,EQ,35.20,36.00,36.80,35.25,35.65,35.80,35.96,49077,1.764580e+11,370,36031.0,0.7342,N,4.0
1,02-01-2020,20MICRONS,EQ,35.80,36.00,36.20,35.10,35.80,35.55,35.51,25846,9.176636e+10,247,17500.0,0.6771,N,4.0
2,03-01-2020,20MICRONS,EQ,35.55,35.85,35.85,34.95,35.20,35.05,35.32,12358,4.365415e+10,241,9896.0,0.8008,N,4.0
3,06-01-2020,20MICRONS,EQ,35.05,35.50,35.50,32.20,34.10,32.80,33.33,42082,1.402800e+11,802,18839.0,0.4477,N,4.0
4,07-01-2020,20MICRONS,EQ,32.80,32.35,34.80,32.35,33.30,33.20,33.73,24770,8.355354e+10,604,10394.0,0.4196,N,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58346,24-06-2020,SHRENIK,EQ,31.65,33.20,33.20,32.00,33.20,33.20,33.08,111120,3.675670e+11,170,86696.0,0.7802,N,1.0
58347,25-06-2020,SHRENIK,EQ,33.20,34.85,34.85,33.15,34.85,34.85,34.84,65870,2.295070e+11,95,45423.0,0.6896,N,1.0
58348,26-06-2020,SHRENIK,EQ,34.85,36.55,36.55,36.30,36.55,36.55,36.52,189992,6.937590e+11,126,136970.0,0.7209,N,1.0
58349,29-06-2020,SHRENIK,EQ,36.55,38.35,38.35,37.25,38.35,38.35,38.27,49560,1.896570e+11,72,38546.0,0.7778,N,1.0
58350,30-06-2020,SHRENIK,EQ,38.35,40.25,40.25,36.45,40.25,40.25,39.47,346782,1.368620e+12,305,321778.0,0.9279,N,1.0

In [31]:
df1['Group'].value_counts()

Y    29672
N    25686
Name: Group, dtype: int64

In [32]:
df1['Quartile'].value_counts()

3.0    14288
2.0    13977
1.0    13773
4.0    13320
Name: Quartile, dtype: int64

## Calculate the daily returns for companies

In [33]:
df = df1.copy()
df

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,Group,Quartile
0,01-01-2020,20MICRONS,EQ,35.20,36.00,36.80,35.25,35.65,35.80,35.96,49077,1.764580e+11,370,36031.0,0.7342,N,4.0
1,02-01-2020,20MICRONS,EQ,35.80,36.00,36.20,35.10,35.80,35.55,35.51,25846,9.176636e+10,247,17500.0,0.6771,N,4.0
2,03-01-2020,20MICRONS,EQ,35.55,35.85,35.85,34.95,35.20,35.05,35.32,12358,4.365415e+10,241,9896.0,0.8008,N,4.0
3,06-01-2020,20MICRONS,EQ,35.05,35.50,35.50,32.20,34.10,32.80,33.33,42082,1.402800e+11,802,18839.0,0.4477,N,4.0
4,07-01-2020,20MICRONS,EQ,32.80,32.35,34.80,32.35,33.30,33.20,33.73,24770,8.355354e+10,604,10394.0,0.4196,N,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58346,24-06-2020,SHRENIK,EQ,31.65,33.20,33.20,32.00,33.20,33.20,33.08,111120,3.675670e+11,170,86696.0,0.7802,N,1.0
58347,25-06-2020,SHRENIK,EQ,33.20,34.85,34.85,33.15,34.85,34.85,34.84,65870,2.295070e+11,95,45423.0,0.6896,N,1.0
58348,26-06-2020,SHRENIK,EQ,34.85,36.55,36.55,36.30,36.55,36.55,36.52,189992,6.937590e+11,126,136970.0,0.7209,N,1.0
58349,29-06-2020,SHRENIK,EQ,36.55,38.35,38.35,37.25,38.35,38.35,38.27,49560,1.896570e+11,72,38546.0,0.7778,N,1.0
58350,30-06-2020,SHRENIK,EQ,38.35,40.25,40.25,36.45,40.25,40.25,39.47,346782,1.368620e+12,305,321778.0,0.9279,N,1.0

In [34]:
#dropping unneccesary columns
df.drop(['Series', 'Volume','Turnover','Trades','Deliverable Volume','%Deliverble'], axis=1, inplace=True)
df

,Date,Symbol,Prev Close,Open,High,Low,Last,Close,VWAP,Group,Quartile
0,01-01-2020,20MICRONS,35.20,36.00,36.80,35.25,35.65,35.80,35.96,N,4.0
1,02-01-2020,20MICRONS,35.80,36.00,36.20,35.10,35.80,35.55,35.51,N,4.0
2,03-01-2020,20MICRONS,35.55,35.85,35.85,34.95,35.20,35.05,35.32,N,4.0
3,06-01-2020,20MICRONS,35.05,35.50,35.50,32.20,34.10,32.80,33.33,N,4.0
4,07-01-2020,20MICRONS,32.80,32.35,34.80,32.35,33.30,33.20,33.73,N,4.0
...,...,...,...,...,...,...,...,...,...,...,...
58346,24-06-2020,SHRENIK,31.65,33.20,33.20,32.00,33.20,33.20,33.08,N,1.0
58347,25-06-2020,SHRENIK,33.20,34.85,34.85,33.15,34.85,34.85,34.84,N,1.0
58348,26-06-2020,SHRENIK,34.85,36.55,36.55,36.30,36.55,36.55,36.52,N,1.0
58349,29-06-2020,SHRENIK,36.55,38.35,38.35,37.25,38.35,38.35,38.27,N,1.0
58350,30-06-2020,SHRENIK,38.35,40.25,40.25,36.45,40.25,40.25,39.47,N,1.0

In [35]:
group_list = df.groupby('Symbol').mean().VWAP
group_list

Symbol
20MICRONS       30.031301
AARTIDRUGS     725.495122
AARTIIND       933.975447
ACE             59.387480
ADANIENT       177.555366
                 ...
WIPRO          214.280244
WSTCSTPAPR     176.238211
ZENSARTECH     124.588780
ZENTEC          46.498780
ZYDUSWELL     1359.181707
Name: VWAP, Length: 488, dtype: float64

In [36]:
symbols = df.Symbol.unique()
len(symbols)

488

In [37]:
sym = symbols[0]
df_test = df.query('Symbol in @sym')
df_test

,Date,Symbol,Prev Close,Open,High,Low,Last,Close,VWAP,Group,Quartile
0,01-01-2020,20MICRONS,35.20,36.00,36.80,35.25,35.65,35.80,35.96,N,4.0
1,02-01-2020,20MICRONS,35.80,36.00,36.20,35.10,35.80,35.55,35.51,N,4.0
2,03-01-2020,20MICRONS,35.55,35.85,35.85,34.95,35.20,35.05,35.32,N,4.0
3,06-01-2020,20MICRONS,35.05,35.50,35.50,32.20,34.10,32.80,33.33,N,4.0
4,07-01-2020,20MICRONS,32.80,32.35,34.80,32.35,33.30,33.20,33.73,N,4.0
...,...,...,...,...,...,...,...,...,...,...,...
118,24-06-2020,20MICRONS,34.05,35.30,35.30,32.00,32.40,32.25,33.09,N,4.0
119,25-06-2020,20MICRONS,32.25,32.00,32.15,30.75,31.45,31.35,31.51,N,4.0
120,26-06-2020,20MICRONS,31.35,31.80,33.00,31.60,32.75,32.30,32.27,N,4.0
121,29-06-2020,20MICRONS,32.30,33.00,35.00,32.40,34.30,34.45,33.89,N,4.0
122,30-06-2020,20MICRONS,34.45,34.70,35.10,32.00,33.25,32.40,33.78,N,4.0

In [38]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 123 entries, 0 to 122
Data columns (total 11 columns):
Date          123 non-null object
Symbol        123 non-null object
Prev Close    123 non-null float64
Open          123 non-null float64
High          123 non-null float64
Low           123 non-null float64
Last          123 non-null float64
Close         123 non-null float64
VWAP          123 non-null float64
Group         123 non-null object
Quartile      123 non-null float64
dtypes: float64(8), object(3)
memory usage: 11.5+ KB

In [39]:
#df.to_csv('temp.csv', encoding='utf-8', index=False)
#df_test['Return'] = df['VWAP'][3]
n = 3
df['VWAP'][n+1]
len(df_test['VWAP'])

123

In [40]:
df_test.loc[0,'Return'] = 0 #remember that dtype is int, not float
df_test.Return = df_test.Return.astype(float)
for i in range(0,len(df_test['VWAP'])-1):
    val = float((df_test.loc[i+1, 'VWAP']-df_test.loc[i, 'VWAP'])/df_test.loc[i, 'VWAP']*100)
    print(val)
    df_test.loc[i+1,'Return'] = val
    
df_test

-1.2513904338153583
-0.5350605463249725
-5.63420158550397
1.200120012001196
-3.0833086273347146
2.8449066992964203
1.8738845925044694
4.029197080291978
1.599775470109459
0.0
-1.3259668508287403
-1.03583426651735
-1.1598302687411701
-1.516886090440759
-1.8018018018017945
-0.26635099141756824
8.694362017804153
-0.27300027300027685
-0.7938680536545282
-1.8763796909492265
-1.2373453318335343
0.08542141230068662
-2.7027027027026906
0.6725146198830317
1.1908219575951313
-0.2583237657864621
0.17266187050360365
-1.7523700086182112
0.02923976608186552
-0.14615609470916183
1.6978922716627796
1.4392630972941851
-0.45402951191828517
-3.3067274800456006
-2.240566037735864
-0.301568154402878
3.8415003024803265
-0.5243227497815314
-1.7569546120058608
-0.26825633383009334
-1.554094441123739
-3.8858530661809274
-0.2526847757422674
-0.7916402786573782
-2.4577082668368964
0.9816753926701595
-4.406999351911859
-4.881355932203394
-5.06058446186742
-11.861861861861863
-3.620102214650773
4.860804242156435
4.509060261272651
-0.9274193548387113
-13.55311355311356
6.214689265536725
-7.1365248226950335
-3.484486873508355
1.4342235410484803
2.7791321306679504
7.305502846299823
2.38726790450928
9.71502590673575
-0.4329004329004306
-4.26877470355732
10.941370767960374
1.3770003721622532
-2.312775330396472
-1.428034573468617
7.586732748760955
-5.776045357902194
4.625799172621288
16.894320632638397
-5.073800738007386
-5.31260123096858
4.071159767362303
-4.470742932281404
-1.0323468685478223
0.2781641168289231
1.803051317614423
0.3746594005449572
-5.361384458771626
0.5019720329867357
-2.961113093114527
-0.07352941176470432
0.07358351729212499
-0.5882352941176475
-2.9585798816568074
-0.07621951219512033
-1.0297482837528589
0.3468208092485544
-1.996927803379415
-2.1551724137931063
0.3604325190228268
1.755786113328018
-0.07843137254901794
0.23547880690737333
0.5481597494126882
1.4797507788161957
0.4221028396009324
3.056935422239194
1.8909899888765354
4.621542940320231
0.10434782608696049
2.2932592077831835
7.778532608695649
-6.523794516230698
-1.3823331085637225
-2.051282051282056
-4.2233856893542665
7.798833819241971
11.697092630155515
-8.807506053268765
1.4271490209093918
3.468586387434563
2.4984187223276266
8.793582227707503
-6.154282473057274
-4.774856452100337
2.4119327197715057
5.020142547257507
-0.32457952198288414

,Date,Symbol,Prev Close,Open,High,Low,Last,Close,VWAP,Group,Quartile,Return
0,01-01-2020,20MICRONS,35.20,36.00,36.80,35.25,35.65,35.80,35.96,N,4.0,0.000000
1,02-01-2020,20MICRONS,35.80,36.00,36.20,35.10,35.80,35.55,35.51,N,4.0,-1.251390
2,03-01-2020,20MICRONS,35.55,35.85,35.85,34.95,35.20,35.05,35.32,N,4.0,-0.535061
3,06-01-2020,20MICRONS,35.05,35.50,35.50,32.20,34.10,32.80,33.33,N,4.0,-5.634202
4,07-01-2020,20MICRONS,32.80,32.35,34.80,32.35,33.30,33.20,33.73,N,4.0,1.200120
...,...,...,...,...,...,...,...,...,...,...,...,...
118,24-06-2020,20MICRONS,34.05,35.30,35.30,32.00,32.40,32.25,33.09,N,4.0,-6.154282
119,25-06-2020,20MICRONS,32.25,32.00,32.15,30.75,31.45,31.35,31.51,N,4.0,-4.774856
120,26-06-2020,20MICRONS,31.35,31.80,33.00,31.60,32.75,32.30,32.27,N,4.0,2.411933
121,29-06-2020,20MICRONS,32.30,33.00,35.00,32.40,34.30,34.45,33.89,N,4.0,5.020143
122,30-06-2020,20MICRONS,34.45,34.70,35.10,32.00,33.25,32.40,33.78,N,4.0,-0.324580

## Testing for one dataframe successful
- now loop and append

In [41]:
df2 = pd.DataFrame()

In [42]:
symbols

array(['20MICRONS', 'AVTNPL', 'AARTIDRUGS', 'AARTIIND', 'RADICO',
       'TRIDENT', 'ADANIENT', 'ADVENZYMES', 'ADVANIHOTR', 'AEGISCHEM',
       'AHLUCONT', 'AKSHOPTFBR', 'ALKALI', 'ALKEM', 'ALKYLAMINE',
       'ALLCARGO', 'ALPHAGEO', 'VIPULLTD', 'ANDHRSUGAR', 'SHIVATEX',
       'APARINDS', 'APCOTEXIND', 'APOLLOHOSP', 'APOLLOTYRE', 'ARMANFIN',
       'ARVIND', 'ASAHIINDIA', 'ASAHISONG', 'ASHIANA', 'ASHOKLEY',
       'ASIANPAINT', 'ASPINWALL', 'ASALCBR', 'ASTRAMICRO', 'ASTRAL',
       'BSL', 'BAJAJELEC', 'FORCEMOT', 'BALPHARMA', 'BALAMINES',
       'BALKRISIND', 'BALMLAWRIE', 'BALRAMCHIN', 'BASML', 'BANARISUG',
       'BANSWRAS', 'BHANDARI', 'BDL', 'BEL', 'BHARATFORG', 'BHEL', 'BPCL',
       'BHARATRAS', 'BHARTIARTL', 'BIL', 'APLAPOLLO', 'BIRLACORPN',
       'BIRLACABLE', 'BLISSGVS', 'BLUEDART', 'BBTC', 'BOMDYEING',
       'BRIGADE', 'BRITANNIA', 'CESC', 'CMICABLES', 'CENTUM', 'CADILAHC',
       'OAL', 'CAPTRUST', 'ZYDUSWELL', 'CEATLTD', 'CENTURYPLY',
       'CENTURYTEX', 'CHAMBLFERT', 'WEIZFOREX', 'EBIXFOREX', 'COMPINFO',
       'COMPUSOFT', 'CCL', 'COSMOFILMS', 'DCMSHRIRAM', 'DFMFOODS',
       'WINDMACHIN', 'DLF', 'DABUR', 'DAMODARIND', 'DECCANCE', 'DEEPIND',
       'DEEPAKFERT', 'DEEPAKNTR', 'CONFIPET', 'DHAMPURSUG', 'LUMAXTECH',
       'DTIL', 'BODALCHEM', 'DPSCLTD', 'DIXON', 'DONEAR', 'DRREDDY',
       'DYNAMATECH', 'DYNPRO', 'EIDPARRY', 'EIHOTEL', 'ELECTCAST',
       'EMMBI', 'ENERGYDEV', 'ESCORTS', 'ESSELPACK', 'EVERESTIND',
       'ALANKIT', 'MCLEODRUSS', 'EVEREADY', 'FIEMIND', 'UFLEX', 'GNA',
       'GALAXYSURF', 'GANESHHOUC', 'GANECOS', 'GARFIBRES', 'GDL', 'GATI',
       'GENESYS', 'GENUSPOWER', 'GLENMARK', 'GODREJAGRO', 'GODREJIND',
       'GRANULES', 'DOLLAR', 'GRASIM', 'GREENPLY', 'GROBTEA', 'GUFICBIO',
       'ADANIPORTS', 'GUJALKALI', 'GAEL', 'MUNJALAU', 'GFLLIMITED',
       'GHCL', 'GIPCL', 'GRPLTD', 'SETCO', 'GSFC', 'EMAMIPAP', 'GULPOLY',
       'HBLPOWER', 'HCLTECH', 'FAIRCHEM', 'HATSUN', 'HERITGFOOD',
       'HESTERBIO', 'HITECHGEAR', 'HITECH', 'HITECHCORP', 'HIKAL', 'HSCL',
       'HIMATSEIDE', 'HINDALCO', 'HAL', 'HINDCOMPOS', 'HINDPETRO', 'HSIL',
       'HISARMETAL', 'HIL', 'IGPL', 'INDLMETER', 'INDIACEM', 'INDIAGLYCO',
       'INDHOTEL', 'INDIANHUME', 'IMFA', 'IOC', 'ICICILOVOL', 'INDOCO',
       'INDRAMEDCO', 'INSECTICID', 'IPCALAB', 'JBMA', 'JKLAKSHMI',
       'UMANGDAIRY', 'JKTYRE', 'JKPAPER', 'JKIL', 'JMCPROJECT', 'JAGRAN',
       'JAICORPLTD', 'JISLJALEQS', 'JASH', 'JAYBARMARU', 'JAYSREETEA',
       'JAYAGROGN', 'JINDALPOLY', 'JSWSTEEL', 'JINDWORLD', 'JUBILANT',
       'JYOTHYLAB', 'KCP', 'KCPSUGIND', 'KNRCON', 'KPRMILL', 'KRBL',
       'KAJARIACER', 'KAKATCEM', 'KALPATPOWR', 'KAMDHENU', 'KDDL',
       'KANORICHEM', 'KEI', 'VISHNU', 'OBEROIRLTY', 'KIRLOSBROS',
       'KIRLFER', 'KITEX', 'BYKE', 'KOTHARIPET', 'KOTHARIPRO',
       'ULTRACEMCO', 'LGBBROSLTD', 'DAAWAT', 'LAMBODHARA', 'SRIPIPES',
       'LT', 'LINCPEN', 'LINCOLN', 'LUMAXIND', 'LUPIN', 'LUXIND', 'MMFL',
       'MRF', 'MADHAV', 'RAMCOCEM', 'MAHSEAMLES', 'VTL', 'M&M',
       'MAITHANALL', 'MANINDS', 'MANGLMCEM', 'MANGCHEFER', 'MRPL',
       'MAYURUNIQ', 'MAZDA', 'MEGH', 'MENONBE', 'MINDACORP', 'MINDAIND',
       'MIRZAINT', 'MIDHANI', 'MOTHERSUMI', 'NCLIND', 'NRAIL',
       'NRBBEARING', 'NACLIND', 'NCC', 'NAHARSPING', 'NDL', 'NFL', 'NHPC',
       'NTPC', 'NBVENTURES', 'NAVNETEDUL', 'NELCAST', 'NEWGEN',
       'NLCINDIA', 'PEL', 'NILAINFRA', 'NILKAMAL', 'NITINSPIN',
       'SWELECTES', 'ONGC', 'OMAXE', 'ORIENTABRA', 'ORIENTCEM',
       'ORIENTBELL', 'ORIENTPPR', 'ORIENTLTD', 'OCCL', 'ORICONENT',
       'PAGEIND', 'VIJIFIN', 'PATINTLOG', 'ALICON', 'PHILIPCARB',
       'PHOENIXLTD', 'MARATHON', 'PLASTIBLEN', 'POKARNA', 'POLYMED',
       'POLYPLEX', 'POWERGRID', 'POWERMECH', 'PTC', 'PPAP', 'PRECWIRE',
       'PREMEXPLN', 'PREMIERPOL', 'PRSMJOHNSN', 'PURVA', 'MOHOTAIND',
       'SARDAEN', 'RSWM', 'RALLIS', 'RAMCOIND', 'RKFORGE', 'RCF',
       'RAYMOND', 'REDINGTON', 'RELAXO', 'RELIANCE', 'REMSONSIND',
       'RICOAUTO', 'ROHLTD', 'RUBYMILLS', 'RUCHIRA', 'RUPA', 'RUSHIL',
       'SCHAND', 'SHK', 'SKMEGGPROD', 'SMSPHARMA', 'SOMANYCERA', 'SRF',
       'SADBHAV', 'SAFARI', 'SAGCEM', 'GULFPETRO', 'SALONA', 'SALZERELEC',
       'SANDHAR', 'SANGAMIND', 'SARLAPOLY', 'SATIA', 'SOTL', 'JINDALSAW',
       'HMVL', 'SIS', 'SHAKTIPUMP', 'ARIHANTSUP', 'SHANKARA', 'CREST',
       'SHOPERSTOP', 'SHREECEM', 'AJMERA', 'SHREYANIND', 'SHREYAS',
       'SIGIND', 'SIMPLEXINF', 'RESPONIND', 'SINTEX', 'SIYSIL', 'ITDCEM',
       'SKIPPER', 'SOBHA', 'SOLARINDS', 'SDBL', 'JTEKTINDIA', 'SEYAIND',
       'SSWL', 'STERTOOLS', 'STRTECH', 'STAR', 'SUBROS', 'SUDARSCHEM',
       'SUNPHARMA', 'SUNCLAYLTD', 'SUNDRMFAST', 'SUNFLAG', 'SUPERHOUSE',
       'SUPRAJIT', 'SUPREMEIND', 'NECLIFE', 'SURYAROSNI', 'SUVEN',
       'SWANENERGY', 'SMLISUZU', 'TIL', 'TTKHLTCARE', 'TVSMOTOR',
       'TVSSRICHAK', 'TPLPLASTEH', 'TALBROAUTO', 'TNPL', 'GPTINFRA',
       'TASTYBITE', 'TATASTEEL', 'TATAMETALI', 'TECHNOFAB', 'HGS',
       'TEXRAIL', 'THANGAMAYL', 'THOMASCOOK', 'TIMETECHNO', 'TOKYOPLAST',
       'TORNTPHARM', 'TCI', 'TRENT', 'TRIVENI', 'TCPLPACK', 'UCALFUEL',
       'UNIPLY', 'UNIVCABLES', 'WABAG', 'VADILALIND', 'VARROC', 'VBL',
       'ASIANTILES', 'VENKEYS', 'TATACOMM', 'VIDHIING', 'VRLLOG',
       'VIKASECO', 'VIMTALABS', 'VINDHYATEL', 'VISAKAIND', 'WATERBASE',
       'WEIZMANIND', 'BLS', 'WELSPUNIND', 'WELCORP', 'WSTCSTPAPR',
       'WHEELS', 'WIPRO', 'ZENTEC', 'ZENSARTECH', 'FINEORG', 'WELENT',
       'UBL', 'FSL', 'JKCEMENT', 'STARCEMENT', 'HTMEDIA', 'GRAVITA',
       'AURIONPRO', 'RML', 'SUTLEJTEX', 'PGIL', 'SORILINFRA', 'ACE',
       'SPAL', 'KEC', 'KUANTUM', 'SRHHYPOLTD', 'GALLISPAT', 'ENDURANCE',
       'TORNTPOWER', 'LAURUSLABS', 'RPGLIFE', 'MAANALU', 'SOMICONVEY',
       'LOTUSEYE', 'AGARIND', 'MOLDTKPAC', 'AHLWEST', 'SHEMAROO',
       'PARAGMILK', 'PCJEWELLER', 'TCIEXP', 'TIINDIA', 'DBL', 'VMART',
       'TBZ', 'MONTECARLO', 'APLLTD', 'IFGLEXPOR', 'HPL', 'AGROPHOS',
       'SALASAR', 'KRIDHANINF', 'MAHESHWARI', 'UFO', 'HGINFRA',
       'INFIBEAM', 'GTPL', 'APEX', 'MEP', 'FLFL', 'APOLLO', 'CAPACITE',
       'GREENLAM', 'PDMJEPAPER', 'MAGADSUGAR', 'AVADHSUGAR', 'BIGBLOC',
       'SHIVAMILLS', 'ONEPOINT', 'PSPPROJECT', 'PRICOLLTD', 'ORIENTELEC',
       'SHRENIK'], dtype=object)

In [43]:
# adding Return and mean_return for the companies
%%capture
for i in range(0,len(symbols)):
    sym = symbols[i]
    df_test = df.query('Symbol in @sym').copy()
    print(df_test)
    df_test['Return'] = np.zeros((len(df_test['VWAP']),1)) #remember that dtype is int, not float
    df_test.Return = df_test.Return.astype(float)
    print(df_test['VWAP'].iloc[1])
    df_test.reset_index(drop=True, inplace=True)
    for j in range(0,len(df_test['VWAP'])-1):
        val = float((df_test['VWAP'].iloc[j+1]-df_test['VWAP'].iloc[j])/df_test['VWAP'].iloc[j]*100)
        df_test['Return'].iloc[j+1] = val
    df_test['mean_return_company'] = np.zeros((len(df_test['VWAP']),1)) #remember that dtype is int, not float
    df_test.mean_return_company = df_test.mean_return_company.astype(float)
    df_test['mean_return_company'] = df_test.Return.mean()
    print(df_test)
    df2 = df2.append(df_test,ignore_index=True)

In [44]:
df2

,Date,Symbol,Prev Close,Open,High,Low,Last,Close,VWAP,Group,Quartile,Return,mean_return_company
0,01-01-2020,20MICRONS,35.20,36.00,36.80,35.25,35.65,35.80,35.96,N,4.0,0.000000,0.041379
1,02-01-2020,20MICRONS,35.80,36.00,36.20,35.10,35.80,35.55,35.51,N,4.0,-1.251390,0.041379
2,03-01-2020,20MICRONS,35.55,35.85,35.85,34.95,35.20,35.05,35.32,N,4.0,-0.535061,0.041379
3,06-01-2020,20MICRONS,35.05,35.50,35.50,32.20,34.10,32.80,33.33,N,4.0,-5.634202,0.041379
4,07-01-2020,20MICRONS,32.80,32.35,34.80,32.35,33.30,33.20,33.73,N,4.0,1.200120,0.041379
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58346,24-06-2020,SHRENIK,31.65,33.20,33.20,32.00,33.20,33.20,33.08,N,1.0,4.518167,0.034439
58347,25-06-2020,SHRENIK,33.20,34.85,34.85,33.15,34.85,34.85,34.84,N,1.0,5.320435,0.034439
58348,26-06-2020,SHRENIK,34.85,36.55,36.55,36.30,36.55,36.55,36.52,N,1.0,4.822044,0.034439
58349,29-06-2020,SHRENIK,36.55,38.35,38.35,37.25,38.35,38.35,38.27,N,1.0,4.791895,0.034439
58350,30-06-2020,SHRENIK,38.35,40.25,40.25,36.45,40.25,40.25,39.47,N,1.0,3.135615,0.034439

In [45]:
df2.tail(20)

,Date,Symbol,Prev Close,Open,High,Low,Last,Close,VWAP,Group,Quartile,Return,mean_return_company
58331,03-06-2020,SHRENIK,17.95,17.80,18.80,17.50,18.50,17.85,17.84,N,1.0,7.147147,0.034439
58332,04-06-2020,SHRENIK,17.85,18.70,18.70,18.35,18.65,18.65,18.66,N,1.0,4.596413,0.034439
58333,05-06-2020,SHRENIK,18.65,19.55,19.55,18.30,19.15,19.15,18.54,N,1.0,-0.643087,0.034439
58334,08-06-2020,SHRENIK,19.15,19.90,20.10,19.00,19.00,19.25,19.65,N,1.0,5.987055,0.034439
58335,09-06-2020,SHRENIK,19.25,20.15,20.20,18.40,20.20,19.65,19.63,N,1.0,-0.101781,0.034439
58336,10-06-2020,SHRENIK,19.65,20.00,20.60,19.65,20.60,20.60,20.31,N,1.0,3.464086,0.034439
58337,11-06-2020,SHRENIK,20.60,20.75,21.60,20.60,21.60,21.60,21.02,N,1.0,3.495815,0.034439
58338,12-06-2020,SHRENIK,21.60,22.60,22.65,21.00,22.65,22.65,21.80,N,1.0,3.710752,0.034439
58339,15-06-2020,SHRENIK,22.65,23.75,23.75,23.75,23.75,23.75,23.75,N,1.0,8.944954,0.034439
58340,16-06-2020,SHRENIK,23.75,24.90,24.90,24.90,24.90,24.90,24.90,N,1.0,4.842105,0.034439
58341,17-06-2020,SHRENIK,24.90,26.10,26.10,25.40,26.10,26.10,26.10,N,1.0,4.819277,0.034439
58342,18-06-2020,SHRENIK,26.10,27.40,27.40,27.40,27.40,27.40,27.40,N,1.0,4.980843,0.034439
58343,19-06-2020,SHRENIK,27.40,28.75,28.75,28.75,28.75,28.75,28.75,N,1.0,4.927007,0.034439
58344,22-06-2020,SHRENIK,28.75,30.15,30.15,30.15,30.15,30.15,30.15,N,1.0,4.869565,0.034439
58345,23-06-2020,SHRENIK,30.15,31.65,31.65,31.65,31.65,31.65,31.65,N,1.0,4.975124,0.034439
58346,24-06-2020,SHRENIK,31.65,33.20,33.20,32.00,33.20,33.20,33.08,N,1.0,4.518167,0.034439
58347,25-06-2020,SHRENIK,33.20,34.85,34.85,33.15,34.85,34.85,34.84,N,1.0,5.320435,0.034439
58348,26-06-2020,SHRENIK,34.85,36.55,36.55,36.30,36.55,36.55,36.52,N,1.0,4.822044,0.034439
58349,29-06-2020,SHRENIK,36.55,38.35,38.35,37.25,38.35,38.35,38.27,N,1.0,4.791895,0.034439
58350,30-06-2020,SHRENIK,38.35,40.25,40.25,36.45,40.25,40.25,39.47,N,1.0,3.135615,0.034439

In [46]:
df2.mean_return_company.isnull().sum()

0

In [47]:
df3 = df2.query('Symbol == "SHRENIK"')
df3

,Date,Symbol,Prev Close,Open,High,Low,Last,Close,VWAP,Group,Quartile,Return,mean_return_company
58228,01-01-2020,SHRENIK,43.05,44.35,46.80,42.55,45.40,44.30,43.93,N,1.0,0.000000,0.034439
58229,02-01-2020,SHRENIK,44.30,46.00,46.00,42.00,43.95,44.30,44.96,N,1.0,2.344639,0.034439
58230,03-01-2020,SHRENIK,44.30,45.55,45.70,41.95,43.85,44.15,43.79,N,1.0,-2.602313,0.034439
58231,06-01-2020,SHRENIK,44.15,45.25,45.40,41.00,41.25,41.40,42.57,N,1.0,-2.786024,0.034439
58232,07-01-2020,SHRENIK,41.40,43.70,43.70,37.30,37.30,37.70,39.82,N,1.0,-6.459948,0.034439
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58346,24-06-2020,SHRENIK,31.65,33.20,33.20,32.00,33.20,33.20,33.08,N,1.0,4.518167,0.034439
58347,25-06-2020,SHRENIK,33.20,34.85,34.85,33.15,34.85,34.85,34.84,N,1.0,5.320435,0.034439
58348,26-06-2020,SHRENIK,34.85,36.55,36.55,36.30,36.55,36.55,36.52,N,1.0,4.822044,0.034439
58349,29-06-2020,SHRENIK,36.55,38.35,38.35,37.25,38.35,38.35,38.27,N,1.0,4.791895,0.034439
58350,30-06-2020,SHRENIK,38.35,40.25,40.25,36.45,40.25,40.25,39.47,N,1.0,3.135615,0.034439

In [48]:
df3.query('Return < 0').shape

(59, 13)

In [49]:
df2.to_csv('post_grouping_data.csv', encoding='utf-8', index=False)